language: node_js
node_js: 
  - '10'
before_install:
  - rm -rf node_modules
  - zip -r app *
  - mkdir -p deploy
  - mv app.zip deploy/app.zip
deploy:
  # aws S3
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_NAME
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: KimPinot/exhibition-client
      branch: production
  # aws CodeDeploy
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_NAME
    key: app.zip
    bundle_type: zip
    application: pinot-ci-cd-app
    deployment_group: pinot-ci-cd-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: KimPinot/exhibition-client
      branch: production
branches:
  only:
    - production
notifications:
  slack:
    secure: FODSUmeZQCgAtLUv0hbXILc7whw3g9dFGBGPc+HKpULYXGL9WSjazKDK1PX9MW4uSuiKgZskuDjfb77XHyU6yb/uqU+H5PlIaNu9FpwK6qp7x4tQKOGOxX7TJEbQ+wggp+H5JyVCcJ983f1XL8akp6lD0ha6XBPnMe3BIvLZWLJbvH31Pa9vYnQJevnNOM2VwkwBY7MmA5Ge4ovSzY3p4Dtr1Njxj0ju8/qJJj0rs35itzJwosY2eIIl2JxoOq3vVdKlVmwnAf6tU+lq+ngHHC3zpdYisYM/982wa7eG2fSs9KKayT6hqGk4c5gey7Hcci09l7cV+kbrNmlw4cEOM3V3iPzjIPhOW+f6Pmcq66glVP7dv6hvuM21mIkuGXFgsCbIp3D5qEdpVg4PnpTNQcmr1qAzPNj+5xXEsYzIudXnF7Jkki8m1m/8iRzynrHGWmHqxnrc0kkod7MtgUPfJNA/la3zRWZLd/c7frXcQGAqJrHa1iTqKHzVIdQUfQ9f9O6ax5tYCHusDndZk+LO82dxumxJQtVE91Tssi9EX2YK+D138QytTRMVnrABnnLSwmONJIEuQGUShSLACu9l4J1PXzP1gu0EQlC6xjz+WmMb37FTmfQSEVD4hnY9cp4XFLML6dJna8rn/DwXuDqqkY8CppRgnxMU4Pf/Gql+ffI=
